# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Descrição'),
        ),
    ]
