# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisan',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ativado'), (1, 'Desativado'), (2, 'Bloqueado')], default=0, verbose_name='Status'),
        ),
    ]
