# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='biography',
            field=models.TextField(verbose_name='Biografia'),
        ),
    ]
